# Generated by Django 4.2.5 on 2023-10-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'benefit',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.BigAutoField(db_column='companyID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('contactnumber', models.TextField(blank=True, db_column='contactNumber', null=True)),
                ('linkedin', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('registrationdate', models.DateField(blank=True, db_column='registrationDate', null=True)),
                ('benefits', models.ManyToManyField(to='backend_project.benefit')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'expertise',
            },
        ),
        migrations.CreateModel(
            name='ExpertiseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'expertise_category',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'industry',
            },
        ),
        migrations.CreateModel(
            name='LanguageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'languagecategory',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.BigAutoField(db_column='candidateID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_type', models.TextField(blank=True, null=True)),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('name', models.TextField(blank=True, null=True)),
                ('preffered_name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('terms_and_conditions', models.BooleanField()),
                ('privacy_policy', models.BooleanField()),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('last_access_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'value',
            },
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'worklocation',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('language', models.ManyToManyField(to='backend_project.languagecategory')),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.BigAutoField(db_column='jobID', primary_key=True, serialize=False)),
                ('is_published', models.BooleanField()),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('jobtype', models.TextField(blank=True, db_column='jobType', null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('salaryrange', models.TextField(blank=True, db_column='salaryRange', null=True)),
                ('appplicationdeadline', models.DateField(blank=True, db_column='appplicationDeadline', null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_project.company')),
                ('expertise', models.ManyToManyField(to='backend_project.expertise')),
                ('language', models.ManyToManyField(to='backend_project.language')),
                ('worklocation', models.ManyToManyField(to='backend_project.worklocation')),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.AddField(
            model_name='expertise',
            name='expertise',
            field=models.ManyToManyField(to='backend_project.expertisecategory'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ManyToManyField(to='backend_project.industry'),
        ),
        migrations.AddField(
            model_name='company',
            name='language',
            field=models.ManyToManyField(to='backend_project.language'),
        ),
        migrations.AddField(
            model_name='company',
            name='value',
            field=models.ManyToManyField(to='backend_project.value'),
        ),
        migrations.AddField(
            model_name='company',
            name='worklocation',
            field=models.ManyToManyField(to='backend_project.worklocation'),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend_project.user')),
                ('location', models.TextField(blank=True, null=True)),
                ('relocation', models.BooleanField()),
                ('education', models.TextField(blank=True, null=True)),
                ('work_experience', models.TextField(blank=True, null=True)),
                ('volunteer_experience', models.TextField(blank=True, null=True)),
                ('courses', models.TextField(blank=True, null=True)),
                ('expertise', models.ManyToManyField(to='backend_project.expertise')),
                ('jobs', models.ManyToManyField(to='backend_project.job')),
                ('language', models.ManyToManyField(to='backend_project.language')),
                ('preffered_roles', models.ManyToManyField(to='backend_project.role')),
            ],
            options={
                'db_table': 'candidate',
            },
        ),
    ]
