# Generated by Django 4.2.5 on 2023-10-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralUser',
            fields=[
                ('UserID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=200)),
            ],
        ),
    ]
