# Generated by Django 4.2.5 on 2023-10-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expertise',
            field=models.ManyToManyField(to='backend_project.expertisecategory'),
        ),
        migrations.AlterField(
            model_name='job',
            name='language',
            field=models.ManyToManyField(to='backend_project.languagecategory'),
        ),
    ]
