# Generated by Django 4.2.5 on 2023-10-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralUser',
            new_name='User',
        ),
    ]
