# Generated by Django 4.2.5 on 2023-10-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_project', '0002_rename_generaluser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
