# Generated by Django 4.2.5 on 2023-10-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_project', '0002_alter_job_expertise_alter_job_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='company',
            name='language',
        ),
        migrations.RemoveField(
            model_name='company',
            name='value',
        ),
        migrations.RemoveField(
            model_name='company',
            name='worklocation',
        ),
        migrations.RemoveField(
            model_name='job',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='job',
            name='language',
        ),
        migrations.RemoveField(
            model_name='job',
            name='worklocation',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='expertise',
            field=models.ManyToManyField(blank=True, null=True, to='backend_project.expertise'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='jobs',
            field=models.ManyToManyField(blank=True, null=True, to='backend_project.job'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='language',
            field=models.ManyToManyField(blank=True, null=True, to='backend_project.language'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='preffered_roles',
            field=models.ManyToManyField(blank=True, null=True, to='backend_project.role'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='relocation',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
