# Generated by Django 4.2.5 on 2023-10-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend_project', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidateid', models.BigAutoField(db_column='candidateID', primary_key=True, serialize=False)),
                ('userid', models.BigIntegerField(db_column='userID')),
                ('jobid', models.BigIntegerField(db_column='jobID')),
                ('headline', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('educationhistory', models.TextField(blank=True, db_column='educationHistory', null=True)),
                ('workexperience', models.TextField(blank=True, db_column='workExperience', null=True)),
                ('certification', models.TextField(blank=True, null=True)),
                ('volunteering', models.TextField(blank=True, null=True)),
                ('preferredjoblocations', models.TextField(blank=True, db_column='preferredJobLocations', null=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('jobapplications', models.TextField(blank=True, db_column='jobApplications', null=True)),
            ],
            options={
                'db_table': 'candidate',
                'managed': False,
            },
        ),
    ]
