# Generated by Django 4.2.5 on 2023-10-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_project', '0003_remove_company_benefits_remove_company_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='expertise',
            field=models.ManyToManyField(blank=True, to='backend_project.expertise'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='backend_project.job'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='language',
            field=models.ManyToManyField(blank=True, to='backend_project.language'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='preffered_roles',
            field=models.ManyToManyField(blank=True, to='backend_project.role'),
        ),
    ]
