# Generated by Django 4.2.5 on 2023-10-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_project', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jobid', models.BigAutoField(db_column='jobID', primary_key=True, serialize=False)),
                ('companyid', models.BigIntegerField(db_column='companyID')),
                ('associationid', models.BigIntegerField(db_column='associationID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('jobtype', models.TextField(blank=True, db_column='jobType', null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('salaryrange', models.TextField(blank=True, db_column='salaryRange', null=True)),
                ('appplicationdeadline', models.DateField(blank=True, db_column='appplicationDeadline', null=True)),
            ],
            options={
                'db_table': 'job',
                'managed': False,
            },
        ),
    ]
