# Generated by Django 4.2.5 on 2023-10-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_project', '0004_alter_candidate_expertise_alter_candidate_jobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
