# Generated by Django 4.2.5 on 2023-10-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_project', '0005_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.BigAutoField(db_column='userID', primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('email', models.TextField(blank=True, null=True)),
                ('firstname', models.TextField(blank=True, db_column='firstName', null=True)),
                ('lastname', models.TextField(blank=True, db_column='lastName', null=True)),
                ('contactnumber', models.TextField(blank=True, db_column='contactNumber', null=True)),
                ('profilepicture', models.TextField(blank=True, db_column='profilePicture', null=True)),
                ('registrationdate', models.DateField(blank=True, db_column='registrationDate', null=True)),
                ('usertype', models.TextField(blank=True, db_column='userType', null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
