# Generated by Django 4.2.5 on 2023-10-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_project', '0006_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_used', models.BooleanField(default=True)),
            ],
        ),
    ]
