# Generated by Django 4.2.5 on 2023-10-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_project', '0007_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
