name: Fly Deploy Staging Backend
on:
  push:
    branches:
      - develop
    paths:
      - 'back-end/**'
jobs:
  deploy:
    name: Deploy staging backend app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy ./back-end/backend -a shift-backend-staging --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STAGING }}
