name: Fly Deploy Production Backend
on:
  push:
    branches:
      - main
    paths:
      - 'back-end/**'
jobs:
  deploy:
    name: Deploy production backend app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -a shift-backend-prod --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
